# config/packages/knpu_oauth2_client.yaml
knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
            use_oidc_mode: false
        facebook:
            type: facebook
            client_id: '%env(FACEBOOK_ID)%'
            client_secret: '%env(FACEBOOK_SECRET)%'
            redirect_route: connect_facebook_check
            redirect_params: { }
            graph_api_version: v12.0